### ISSUE TITLE
Multiline entries give 'unexpected content' error

### ISSUE THREAD

**Issue by OtherCroissant** [smortex/yaml-sort#23]
Hi, really appreciate the speed of yaml-sort compared to the i18n-normalize which can only sort all the locale files at once.

We have yaml entries which are multi line text entries, and I think this should be valid yml. Unfortunately, yaml-sort does break on these entries.

```
test:
  testtest: blob
  testblaat: a long string which is devided over multiple lines to optimize readability for people with small 120x80 console
    screens and do not want to buy larger screens with more columns for characters
```

This results in a `unexpected content` error:

<img width="601" alt="Scherm­afbeelding 2023-01-06 om 15 57 01" src="https://user-images.githubusercontent.com/5735726/211038350-97092b3e-77bc-42dd-8f7a-b748f40a36da.png">

Could you have a look at this?
