### ISSUE TITLE
Empty array value support

### ISSUE THREAD

**Issue by OtherCroissant** [smortex/yaml-sort#29]
yet another challenge....

This fails with 
```
7 unexpected KEY
  day_names:
^~~~~~~~~~~~`:
```

```
test:
  abbr_month_names:
  -
  - gen
  - feb
  day_names:
  - domenica
  - lunedì
```

This works:

```
test:
  abbr_month_names:
  - ''
  - gen
  - feb
  day_names:
  - domenica
  - lunedì

```

Although both are valid yml...

Thanks!
