### ISSUE TITLE
Option to ignore references?

### ISSUE THREAD

**Issue by gstokkink** [smortex/yaml-sort#32]
Right now, when you try to sort a YAML file, you get the following error message:

```
test.yml:8: '<<:' references are not sortable:
  <<: *foo
  ^~~
```

An option to ignore such references would be nice to have. Now such YAML files cannot be sorted at all.

**Comment by smortex** [comment]
I guess we can do *some* sorting, e.g. when given:

```yaml
data:
  d: d
  a: a
  <<: *foo
  c: c
  b: b
```

we can generate:

```yaml
data:
  a: a
  d: d
  <<: *foo
  b: b
  c: c
```

That is sort each group of items between the beginning of a dictionary, the end of a dictionary, or a reference. `<<` would act as a stop token when sorting.

Would that work for you? Do you see any pitfall?

**Comment by gstokkink** [comment]
@smortex I think I would prefer to sort the merge keys to the top of the hash, then sort the rest. So something like this:

 ```
 data:
  <<: *foo
  a: a
  b: b
  c: c
  d: d
  ```

Reason being that we do not know exactly what is being merged, plus I think it's the idiom to keep merge keys to the top.

@OtherCroissant what do you think?

**Comment by smortex** [comment]
In that case, that would break things like:

```yaml
foo:
  a: 42
data:
  d: d
  a: a
  <<: *foo
  c: c
  b: b
```

here, `data.a` = 42, but with your sorting, `data.a` = "a":

```yaml
foo:
  a: 42
data:
  <<: *foo
  a: a
  b: b
  c: c
  d: d
```

Also, the "correct" sorting should output `data` before `foo`, and this reordering is not possible with merges… Maybe there is no reliable sorting mechanism that can exist for this use case…
